### ISSUE TITLE
Replayable Action Log!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#112]
At present the MVP is deliberately simple.
There is no version history for `item.text` so if you update something the previous version is _gone_.
How do we implement the ability to replay all actions taken in the App?
So that we have an **`undo`** button for every change that is made.

Is there anything in https://github.com/dwyl/alog we can use?
Or do we need to rethink this from first principals. 

`#discuss`! 💬 🙏

**Comment by SimonLab** [comment]
I'll have to look again at alog and do some research first on how to implement/use an history of actions.

**Comment by nelsonic** [comment]
Related to: https://github.com/dwyl/app/issues/276

**Comment by nelsonic** [comment]
Closing in favour of https://github.com/dwyl/app/issues/276 💭
