### ISSUE TITLE
Remove `people` table completely? ✂️ 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#118]
@SimonLab made a _very_ valid/insightful point in https://github.com/dwyl/app-mvp/issues/115#issuecomment-1206190867 ... 💭 
At present the `people` table is simply ***mirroring*** the contents of `people` from `auth` 
via the `JWT` when the person successfully authenticates ...
i.e. we are storing the data in the MVP App and don't actually _need_ to.

# Two Questions: 

# 1. Will it be _confusing_ to a complete beginner to <br />_not_ have the `people` table in the MVP?

At present we have the following ERD as part of the update: https://github.com/dwyl/app-mvp/issues/89#issuecomment-1183866847
![erd-with-people](https://user-images.githubusercontent.com/194400/178869576-c6aff9d7-1bc3-43ff-80ac-71b3e86363dd.png)

To _me_ this makes it reasonably clear what the link between the tables is.
But if we were to _remove_ `people`, would it still be clear that an `item` "belongs" to a `person`?

Removing the `people` table will not alter the _functionality_ of the MVP ... 📱 📝 ⏳ ✅ 
But it will result in less code & tests. 🎉 
So I'm very much considering it. 💭 

# 2. Will we have a `people` table in the "real" [App](https://github.com/dwyl/app)? 

Once we have finished testing the MVP and we port the code over to the "real" [App](https://github.com/dwyl/app),
do we _want_ to have a `people` table? or can we exclude it completely and have a separation of concerns?
i.e. only have the `items.person_id` reference and store all personal data _encrypted_ in the `auth` App?

**Comment by nelsonic** [comment]
Given that the goal of this repo/project is the _minimum_ code, I'm leaning toward removing the table/schema. 💭

**Comment by SimonLab** [comment]
My preference would also be to remove the `people` table for now. Like you said, less code is good!
I don't think it would be to time consuming to add back a table if we need it later on, at the moment `auth` provides all the info necessary for the MVP to work.

**Comment by nelsonic** [comment]
@SimonLab thank you for suggesting the removal. 👌 
I'm happy to get it done now as part of my `README.md` update ... 👨‍💻
The good news is we can just delete it from the Fly App without any consequences. (once the foreign keys are removed)
But I totally _agree_ I think the MVP will be substantially simplified by removing it!

**Comment by nelsonic** [comment]
Successfully removes `people` schema/table from the project: https://github.com/dwyl/app-mvp/commit/316929c39888ea3285f6d42324844f95231f588e ✂️ 

New ERD:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/194400/183075195-c1b50232-5988-47cb-ad18-47dfd4c0bcc3.png">

It's almost _comically_ simple compared to the previous version of the MVP: https://github.com/dwyl/app-mvp/issues/89#issuecomment-1163339664

![image](https://user-images.githubusercontent.com/194400/175084956-0aa9c997-a65b-4688-92fb-19f5126064c0.png)

Everything still works as expected. 📝  ⏳ ✅ 
Thanks again for the suggestion. 👌

**Comment by SimonLab** [comment]
I haven't looked in details at the commit to remove the `people` table yet, but I'm thinking that if the `person_id` defined on the items can be null, I think we can also remove the seeds data used to describe guest users: If the person_id is not null is is linked to a loggedin user, otherwise if null it is a public item and created linked to "guest".

Just saw you already removed the seeds: https://github.com/dwyl/app-mvp/blob/phoenix-1.6-2022-refresh-issue-%2389/priv/repo/seeds.exs :+1:
