### ISSUE TITLE
Feat: View Archived `items`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/app-mvp#119]
# Story

As a person using the MVP to track `time` taken on a task (`item`),
I want to see the completed (**`archived`**) `items`,
So that I can see the ***history*** of `items` I've worked on (_and **completed**_)

At present when an `item` is **`archived`** it disappears from the UI and there is no way to view it.
This was both deliberate to reduce UI clutter and an obvious oversight 
because if people cannot _see_ their archived `items` they don't have _trust_ in the system
to use it as their "second brain". 

@SimonLab want to pair on this or pick it up solo? 
Very similar to https://github.com/dwyl/phoenix-liveview-todo-list-tutorial#9-footer-navigation

**Comment by SimonLab** [comment]
I'm happy to have a go at this today, once I've merged your PR.
I think we can use LiveView to toggle between current/archived items.
I'm not sure yet where we should display the links, footer, navbar but I'll have a try.

**Comment by SimonLab** [comment]
Feature implemented with https://github.com/dwyl/app-mvp/pull/125
It allows to filter items by "all", "active", "done" and "archived"
I need to finish the PR by adding some css and updating the BUILDIT file

**Comment by SimonLab** [comment]
#125 is now merged and the items are filtered by status.
One small UI enhancement I want to add is to underline the selected filter to make it more obvious which items are currently displayed

**Comment by nelsonic** [comment]
@SimonLab please see new issue: https://github.com/dwyl/app-mvp/issues/126 💭

**Comment by nelsonic** [comment]
Current UX: 
![only-show-footer-nav-when-items-1](https://user-images.githubusercontent.com/194400/184524490-c9b9c7ab-745b-494f-a800-11044be5d9e7.gif)
