### ISSUE TITLE
`mix deps.get` crashes on new cloned project

### ISSUE THREAD

**Issue by tadasajon** [dwyl/app-mvp#78]
1. I cloned the repo
2. I switched to the same version of elixir specified in the `mix.exs` file
3. I tried to run `mix deps.get`
4. I got `** (FunctionClauseError) no function clause matching in String.replace/4` along with an ugly crash

**Comment by nelsonic** [comment]
This was addressed last year. No longer an issue in the latest version of `auth_plug` or the MVP #90 ✅
