### ISSUE TITLE
App does not show a Google login option on localhost:4000

### ISSUE THREAD

**Issue by tadasajon** [dwyl/app-mvp#79]
I followed the directions in the README and got past all the installation steps.  But when I start the app, I don't see something resembling the screenshot in the README, which has a login button for Google.  In fact, I noticed that there is no package relating to Google OAuth installed in the `deps/` folder.  This is what I see instead: 
![M1 2021-10-07 at 5 21 52 PM](https://user-images.githubusercontent.com/86680401/136464419-a097ebfe-0523-4156-8bf5-8f95d335c65e.png)

**Comment by nelsonic** [comment]
Hopefully this has been addressed by #90 🤞 
Thanks again for opening this issue to remind us that the MVP _suuuuucked_! 👌
